language: cpp

dist: trusty

compiler:
  - gcc

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

install:
  - CC=gcc-7

script:
  - cmake . -G "Unix Makefiles"
  - make

cache:
  build: true