# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  PL0_config = debug
endif
ifeq ($(config),release)
  PL0_config = release
endif

PROJECTS := PL0

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

PL0:
ifneq (,$(PL0_config))
	@echo "==== Building PL0 ($(PL0_config)) ===="
	@${MAKE} --no-print-directory -C . -f PL0.make config=$(PL0_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f PL0.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   PL0"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"